apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pihole
  namespace: argocd
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: pihole
  project: default
  sources:
  - repoURL: 'https://github.com/mcapala-homelab/pihole.git'
    targetRevision: master
    ref: values
  - repoURL: 'https://mojo2600.github.io/pihole-kubernetes'
    chart: pihole
    targetRevision: 2.24.0
    helm:
      valueFiles:
      - $values/values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true

