DNS1: "1.1.1.1"
DNS2: "1.0.0.1"

privileged: true
hostNetwork: true
hostname: "hole"
webHttp: "18080"
webHttps: "18443"

admin:
  existingSecret: pihole-password

dnsmasq:
  staticDhcpEntries:
    - dhcp-host=2C:CF:67:14:09:52,192.168.1.11,rpi5-2
    - dhcp-host=2C:CF:67:14:09:53,192.168.1.141,rpi5-2_wifi
    - dhcp-host=D8:3A:DD:02:0E:47,192.168.1.142,rpi4-1_wifi
    - dhcp-host=D8:3A:DD:02:0E:46,192.168.1.12,rpi4-1

serviceWeb:
  http:
    port: "18080"
  https:
    port: "18443" 

persistentVolumeClaim:
  enabled: "true"

podDnsConfig:
  enabled: true
  policy: "None"
  nameservers:
  - 127.0.0.1
  - 1.1.1.1

extraEnvVars:
  TZ: "Europe/Warsaw"
  DHCP_ACTIVE: "true"
  DHCP_START: "192.168.1.10"
  DHCP_END: "192.168.1.150"
  DHCP_ROUTER: "192.168.1.1"
  DHCP_rapid_commit: "true"
  INTERFACE: "eth0"
  DNSMASQ_LISTENING: "single"
  FTLCONF_LOCAL_IPV4: "127.0.0.1"
